'use strict';
const C=window.LoveCore,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const icon=(name)=>`<svg aria-hidden="true"><use href="#i-${name}"/></svg>`;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const defaults={name1:'小予',name2:'小安',start:'2024-05-20',quote:'从此，三餐四季，温柔有趣，都与你有关。'};
function read(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback;}catch{return fallback;}}
let settings=read('our-days-settings',defaults);
if(!settings||!C.validDate(settings.start)||C.daysBetween(settings.start)<0||!settings.name1||!settings.name2)settings={...defaults};
let events=read('our-days-events',null)||[{id:'together',title:'我们的恋爱纪念日',date:settings.start,annual:true},{id:'first-trip',title:'第一次一起旅行',date:'2024-10-01',annual:true},{id:'christmas',title:'一起过的圣诞节',date:'2024-12-25',annual:true}];
if(!Array.isArray(events))events=[];
let favorites=read('our-days-favorites',[]);if(!Array.isArray(favorites))favorites=[];
let hideDemo=read('our-days-hide-demo',false),memories=[],filter='all',search='',dbReady=false,toastTimer,objectUrls=[],uploadUrls=[],shareUrl=null;
const demo=[
 {id:'demo-beach',title:'和你一起，去看海',date:'2026-08-23',place:'海边 · 日落时分',note:'风是温柔的，海也是。\n身边的你，更是。',kind:'image',src:'assets/beach.jpg'},
 {id:'demo-coffee',title:'一杯咖啡，两个人的周末',date:'2026-08-16',place:'街角咖啡店',note:'不赶时间，今天只负责喜欢你。',kind:'image',src:'assets/coffee.jpg'},
 {id:'demo-mountain',title:'山野之间，都是自由',date:'2026-08-09',place:'属于我们的远方',note:'一起走过的路，都算数。',kind:'image',src:'assets/mountain.jpg'},
 {id:'demo-flowers',title:'平凡日子里的小浪漫',date:'2026-07-28',place:'我们的小家',note:'你说路过花店的时候，想起了我。',kind:'image',src:'assets/flowers.jpg'},
 {id:'demo-sunset',title:'收藏一整个橘子味的黄昏',date:'2026-07-19',place:'散步回家的路上',note:'日落尤其温柔，人间皆是浪漫。',kind:'image',src:'assets/sunset.jpg'}
].map(m=>({...m,demo:true}));
function toast(message){clearTimeout(toastTimer);$('#toast').textContent=message;$('#toast').classList.add('show');toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3800);}
function persist(key,value){localStorage.setItem(key,JSON.stringify(value));}
function niceDate(s){return s.replaceAll('-','.');}
function updateCounter(){const now=new Date();$('#days').textContent=String(Math.max(0,C.daysBetween(settings.start,now))).padStart(3,'0');$('#hours').textContent=String(now.getHours()).padStart(2,'0');$('#minutes').textContent=String(now.getMinutes()).padStart(2,'0');$('#seconds').textContent=String(now.getSeconds()).padStart(2,'0');}
function renderSettings(){ $('#couple-names').innerHTML=`${esc(settings.name1)} <em>&</em> ${esc(settings.name2)}`;$('#avatar1').textContent=[...settings.name1].at(-1);$('#avatar2').textContent=[...settings.name2].at(-1);$('#love-quote').textContent=settings.quote;$('#start-caption').textContent='SINCE '+niceDate(settings.start);updateCounter();}
function renderEvents(){const sorted=events.map(e=>({...e,...C.nextOccurrence(e.date,e.annual)})).sort((a,b)=>(a.past-b.past)||a.days-b.days);$('#anniversary-grid').innerHTML=sorted.length?sorted.map((e,i)=>`<article class="anniversary-card"><div class="event-top"><span class="event-icon">${icon(i===0?'heart':i===1?'calendar':'spark')}</span><span class="event-tag">${e.past?'珍藏的回忆':e.days===0?'就是今天':i===0?'最近的期待':e.annual?'每年 · 都要记得':'值得纪念'}</span></div><h3 class="event-title">${esc(e.title)}</h3><span class="event-date">${niceDate(C.localDate(e.date))}${e.annual?' · 每年重复':''}</span><div class="event-bottom">${e.past?'已过去':e.days===0?'就在':'还有'}<strong class="event-number">${Math.abs(e.days)}</strong>天<span>${e.past?'a lovely memory':e.days===0?'a special day':'can’t wait'}</span></div><button class="icon-button delete-event" data-delete-event="${esc(e.id)}" aria-label="删除${esc(e.title)}">${icon('trash')}</button></article>`).join(''):`<div class="event-empty">还没有纪念日，把第一个值得期待的日子记下来吧。<br><button class="text-button" data-action="event">添加纪念日 ${icon('plus')}</button></div>`;}
function allMemories(){return [...memories,...(hideDemo?[]:demo)].sort((a,b)=>b.date.localeCompare(a.date));}
function renderMemories(){const all=allMemories();const list=all.filter(m=>(filter==='all'||filter===m.kind||(filter==='favorite'&&favorites.includes(m.id)))&&[m.title,m.note,m.place].some(v=>v.toLowerCase().includes(search.toLowerCase())));$('#memory-count').textContent=all.length;$('#memory-grid').innerHTML=list.map(m=>`<article class="memory-card ${m.demo?'demo':''}"><button class="memory-cover" data-open="${esc(m.id)}" aria-label="查看${esc(m.title)}">${m.kind==='video'?`<video src="${esc(m.src)}#t=0.1" preload="metadata" muted playsinline></video><span class="play-overlay">${icon('play')}</span>`:m.kind==='text'?`<div style="padding:32px;white-space:pre-wrap;overflow-wrap:anywhere;color:#754e58">${esc(m.note||m.title)}</div>`:`<img src="${esc(m.src)}" alt="${esc(m.title)}" loading="lazy">`}<span class="media-badge">${icon(m.kind==='video'?'play':'camera')}${m.demo?'示例照片':m.kind==='video'?'视频':m.kind==='text'?'文字':'照片'}</span></button><div class="memory-info"><span class="memory-date">${niceDate(m.date)}</span><h3>${esc(m.title)}</h3><button class="favorite-button ${favorites.includes(m.id)?'liked':''}" data-favorite="${esc(m.id)}" aria-label="${favorites.includes(m.id)?'取消收藏':'收藏'}${esc(m.title)}" aria-pressed="${favorites.includes(m.id)}">${icon('heart')}</button><p>${esc(m.note)}</p><span class="memory-meta">${icon('pin')}${esc(m.place||'我们的小世界')}</span></div></article>`).join('')+(list.length?'':`<div class="empty-memories">${search?'没有找到这段回忆，试试别的关键词。':filter==='video'?'第一段关于我们的视频，等你来记录。':filter==='favorite'?'点亮照片旁的爱心，收藏那些心动瞬间。':'这里空着，等你写下我们的故事。'}</div>`)+`<button class="memory-card add-memory" data-action="upload">${icon('plus')}<strong>下一份心动，由你记录</strong><small>照片 / 视频 / 那些小小的幸福</small></button>`;
$('#collection-note').textContent=hideDemo?'回忆保存在当前浏览器 · 在「数据与备份」中导出珍藏':`已记录 ${memories.length} 个真实瞬间 · 当前展示含示例照片，可在设置中隐藏`;
$$('.memory-cover img').forEach(img=>img.addEventListener('error',()=>{img.parentElement.classList.add('media-fallback');img.alt='图片暂时无法加载';},{once:true}));}
async function reloadMedia(){memories=await MemoryStore.all(); if(CloudSync?.configured()){try{const remote=await CloudSync.list(); const localIds=new Set(memories.map(x=>x.id)); memories=[...memories,...remote.filter(x=>!localIds.has(x.id)).map(x=>({...x,remote:true,src:x.src||x.url}))]}catch{}} objectUrls.forEach(URL.revokeObjectURL);objectUrls=[];memories=memories.map(m=>{if(m.blob){const src=URL.createObjectURL(m.blob);objectUrls.push(src);return {...m,src};}return m;});renderMemories();}
function openDialog(title,html){$('#dialog-title').textContent=title;$('#dialog-content').innerHTML=html;if(!$('#editor').open)$('#editor').showModal();document.body.classList.add('no-scroll');}
function closeDialog(){ $('#editor').close();uploadUrls.forEach(URL.revokeObjectURL);uploadUrls=[];if(shareUrl){URL.revokeObjectURL(shareUrl);shareUrl=null;}document.body.classList.remove('no-scroll');}
function errorForm(message){const el=$('#form-error');if(el){el.textContent=message;el.scrollIntoView({block:'nearest'});}else toast(message);}
const errorSlot='<p id="form-error" class="form-error" role="alert"></p>';
function openSettings(){openDialog('关于我们',`<form id="settings-form"><div class="form-grid"><label class="field">你的名字<input name="name1" maxlength="20" value="${esc(settings.name1)}" required></label><label class="field">TA 的名字<input name="name2" maxlength="20" value="${esc(settings.name2)}" required></label></div><label class="field">故事开始的那一天<input name="start" type="date" min="1900-01-01" max="${C.localDate()}" value="${esc(settings.start)}" required></label><label class="field">写给彼此的一句话<textarea name="quote" maxlength="120">${esc(settings.quote)}</textarea></label><p class="form-hint">计时从所选日期的本地时间 00:00 开始，当天为相爱第 0 天。名字与日期初始为示例，可以随时更改。</p><div class="data-panel cloud-panel"><h3>两个人的共享空间</h3><p class="form-hint">输入同一个邀请码，你们就能在不同手机看到共同上传的照片、视频和文字。邀请码只保存在本机。</p><label class="field">共享邀请码<input name="room" maxlength="40" value="${esc(CloudSync?.room||'')}" placeholder="例如 LOVE-AB12CD"></label><p class="form-hint">当前状态：<strong id="cloud-status">${CloudSync?.configured()?'已连接':'未连接'}</strong></p><div class="data-buttons"><button type="button" class="button button-outline" data-action="connect-cloud">连接共享空间</button><button type="button" class="button button-outline" data-action="disconnect-cloud">断开连接</button></div></div>${errorSlot}<div class="form-actions"><button class="button" type="submit">保存我们的故事 ${icon('heart')}</button></div></form><div class="data-panel"><h3>好好收藏，不止此刻</h3><p class="form-hint">照片视频仅保存在当前设备的这个浏览器中，不会自动同步到另一台设备。清理浏览器数据可能导致丢失，建议定期导出备份；把备份交给 TA，即可在同一网站导入查看。</p><div class="data-buttons"><button class="button button-outline" data-action="export">导出完整备份</button><button class="button button-outline" data-action="import">导入回忆备份</button></div><button class="text-button" data-action="toggle-demo">${hideDemo?'显示灵感示例照片':'隐藏灵感示例照片'}</button></div>`);$('#settings-form').onsubmit=e=>{e.preventDefault();try{const f=new FormData(e.target);const next={name1:f.get('name1').trim(),name2:f.get('name2').trim(),start:f.get('start'),quote:f.get('quote').trim()}; if(f.get('room')!==null) CloudSync.setRoom(f.get('room')); if(!next.name1||!next.name2)throw new Error('请填上两个人的名字');if(!C.validDate(next.start)||C.daysBetween(next.start)<0)throw new Error('请选择今天或之前的有效日期');persist('our-days-settings',next);settings=next;events=events.map(v=>v.id==='together'?{...v,date:next.start}:v);persist('our-days-events',events);renderSettings();renderEvents();closeDialog();toast('已保存，每一天都从这里开始 ♡');}catch(err){errorForm(err.message||'保存失败，请检查浏览器存储权限');}};}
function openEvent(){openDialog('给期待一个日期',`<form id="event-form"><label class="field">纪念日名称<input name="title" placeholder="例如：我们的第一次约会" maxlength="60" required autofocus></label><label class="field">值得记住的日期<input type="date" name="date" min="1900-01-01" max="2200-12-31" value="${C.localDate()}" required></label><label class="check-label"><input name="annual" type="checkbox" checked>每年重复庆祝</label><p class="form-hint" style="margin-top:15px">每年重复的日子会自动计算下一次倒计时。2 月 29 日在平年按 2 月 28 日纪念。</p>${errorSlot}<div class="form-actions"><button type="button" class="button button-outline" data-action="close">再想一下</button><button class="button" type="submit">收藏这个日子</button></div></form>`);$('#event-form').onsubmit=e=>{e.preventDefault();try{const f=new FormData(e.target),title=f.get('title').trim(),date=f.get('date');if(!title||!C.validDate(date))throw new Error('请填写名称和有效日期');const next=[...events,{id:crypto.randomUUID(),title,date,annual:f.get('annual')==='on'}];persist('our-days-events',next);events=next;renderEvents();closeDialog();toast('又多了一个值得期待的日子');}catch(err){errorForm(err.message);}};}
function openUpload(){if(!dbReady){toast('浏览器存储不可用，请用启动脚本打开网站后重试');return;}openDialog('把此刻，留给以后的我们',`<form id="upload-form"><label class="field upload-zone">照片或视频（可不选，支持只写文字）<input type="file" name="media" accept="image/jpeg,image/png,image/webp,image/gif,video/mp4,video/webm,video/ogg" multiple><div class="upload-preview" id="upload-preview"></div><span class="form-hint">支持 JPG / PNG / WebP / GIF / MP4 / WebM / OGG，单个文件不超过 50 MB，一次最多 10 个。</span></label><label class="field">给这段回忆起个名字<input name="title" maxlength="100" placeholder="选填，不填会自动命名"></label><div class="form-grid"><label class="field">发生在哪一天<input name="date" type="date" min="1900-01-01" max="${C.localDate()}" value="${C.localDate()}" required></label><label class="field">在哪里<input name="place" maxlength="60" placeholder="我们的小世界"></label></div><label class="field">想记住的话<textarea name="note" maxlength="500" placeholder="天气、心情，和今天的你……"></textarea></label>${errorSlot}<div class="form-actions"><button type="button" class="button button-outline" data-action="close">取消</button><button class="button" type="submit">保存这份心动 ${icon('heart')}</button></div></form>`);
const input=$('#upload-form input[type=file]');input.onchange=()=>{uploadUrls.forEach(URL.revokeObjectURL);uploadUrls=[];$('#upload-preview').replaceChildren();for(const file of [...input.files].slice(0,10)){const el=document.createElement(file.type.startsWith('video/')?'video':'img');const url=URL.createObjectURL(file);uploadUrls.push(url);el.src=url;el.muted=true;el.title=file.name;$('#upload-preview').append(el);}};
$('#upload-form').onsubmit=async e=>{e.preventDefault();const button=e.target.querySelector('[type=submit]');try{const files=[...input.files];if(files.length>10)throw new Error('一次最多选择 10 个文件');for(const file of files){if(!/^(image\/(jpeg|png|webp|gif)|video\/(mp4|webm|ogg))$/.test(file.type))throw new Error('有文件格式暂不支持，请换用列出的格式');if(file.size>50*1024*1024)throw new Error('单个文件不能超过 50 MB，请压缩后重试');if(!file.size)throw new Error('不能上传空文件');}const f=new FormData(e.target),title=f.get('title').trim()||f.get('note').trim().slice(0,30)||(files.length?'日常记录':''),date=f.get('date');if(!title)throw new Error('请写一点文字，或选择照片、视频');if(!C.validDate(date)||C.daysBetween(date)<0)throw new Error('日期不能晚于今天');button.disabled=true;button.textContent='正在珍藏…';const batch=(files.length?files:[new File([f.get('note').trim()||title],'note.txt',{type:'text/plain'})]).map((file,index)=>({id:crypto.randomUUID(),title:files.length>1?`${title.slice(0,90)} · ${index+1}`:title,date,place:f.get('place').trim(),note:f.get('note').trim(),kind:files.length?(file.type.startsWith('video/')?'video':'image'):'text',blob:file,filename:file.name}));await MemoryStore.write(batch); if(CloudSync?.configured()){for(const item of batch){try{await CloudSync.upload({id:item.id,title:item.title,date:item.date,place:item.place,note:item.note,kind:item.kind,filename:item.filename},item.blob)}catch(err){toast('本机已保存，但云端同步失败：'+err.message)}}} await reloadMedia();closeDialog();filter='all';search='';$('#search').value='';$$('.filter').forEach(b=>{b.classList.toggle('active',b.dataset.filter==='all');b.setAttribute('aria-pressed',String(b.dataset.filter==='all'));});renderMemories();toast(`已收藏 ${batch.length} 个珍贵瞬间 ♡`);$('#memories').scrollIntoView({behavior:'smooth'});}catch(err){errorForm(err.name==='QuotaExceededError'?'浏览器空间不足，请先导出备份，再清理不需要的内容':err.message||'保存失败，请重试');button.disabled=false;button.textContent='保存这份心动';}};}
function openMemory(id){const m=allMemories().find(m=>m.id===id);if(!m)return;$('#lightbox-content').innerHTML=`${m.kind==='video'?`<video class="lightbox-media" src="${esc(m.src)}" controls autoplay playsinline></video>`:m.kind==='text'?'':`<img class="lightbox-media" src="${esc(m.src)}" alt="${esc(m.title)}">`}<div class="lightbox-detail"><span class="memory-date">${niceDate(m.date)} · ${esc(m.place||'我们的小世界')}${m.demo?' · 示例照片':''}</span><h2>${esc(m.title)}</h2><p>${esc(m.note)}</p><div class="lightbox-actions"><button class="text-button" data-favorite="${esc(m.id)}">${icon('heart')} ${favorites.includes(m.id)?'已收藏 · 点击取消':'收藏这份心动'}</button>${m.demo?'<span class="form-hint">示例内容，可在设置中隐藏</span>':`<div><button class="text-button" data-share-memory="${esc(m.id)}">${icon('share')}分享文件</button> <button class="icon-button" data-delete-memory="${esc(m.id)}" aria-label="删除这段回忆">${icon('trash')}</button></div>`}</div></div>`;$('#lightbox').dataset.memoryId=id;$('#lightbox').showModal();document.body.classList.add('no-scroll');}
function closeLightbox(){const v=$('#lightbox video');if(v)v.pause();$('#lightbox').close();$('#lightbox-content').replaceChildren();document.body.classList.remove('no-scroll');}
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
function blobData(blob){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(reader.error);reader.readAsDataURL(blob);});}
async function exportBackup(button){if(!dbReady)return toast('本机存储未能打开，暂时无法导出');if(button)button.disabled=true;try{const saved=await MemoryStore.all(),items=[];for(const m of saved){const {blob,...meta}=m;items.push({...meta,data:await blobData(blob)});}const backup={version:1,settings,events,memories:items,favorites,hideDemo};download(new Blob([JSON.stringify(backup)],{type:'application/json'}),`朝暮-回忆备份-${C.localDate()}.json`);toast('备份已导出，记得好好收藏');}catch(err){toast('导出失败：'+(err.message||'请稍后再试'));}finally{if(button)button.disabled=false;}}
async function importBackup(file){if(!file)return;if(!dbReady)return toast('本机存储未能打开，暂时无法导入');try{if(file.size>500*1024*1024)throw new Error('备份超过 500 MB，请选择较小的备份');const b=C.validateBackup(JSON.parse(await file.text()));if(!confirm(`导入将替换本机当前的情侣信息、${events.length} 个纪念日和 ${memories.length} 个真实瞬间。请确认已导出旧备份。继续导入 ${b.events.length} 个纪念日和 ${b.memories.length} 个瞬间？`))return;const records=b.memories.map(m=>{const {data,...rest}=m;const [header,base64]=data.split(',');const bin=atob(base64);const bytes=Uint8Array.from(bin,c=>c.charCodeAt(0));if(bytes.length>50*1024*1024)throw new Error('备份含超过 50 MB 的媒体文件');return {...rest,blob:new Blob([bytes],{type:header.slice(5,header.indexOf(';'))})};});const oldSettings=settings,oldEvents=events;try{persist('our-days-settings',b.settings);persist('our-days-events',b.events);await MemoryStore.write(records,true);}catch(err){persist('our-days-settings',oldSettings);persist('our-days-events',oldEvents);throw err;}settings=b.settings;events=b.events;favorites=Array.isArray(b.favorites)?b.favorites.filter(id=>typeof id==='string'):[];hideDemo=Boolean(b.hideDemo);persist('our-days-favorites',favorites);persist('our-days-hide-demo',hideDemo);await reloadMedia();renderSettings();renderEvents();closeDialog();toast('回忆已导入，欢迎回到我们的小宇宙');}catch(err){toast('无法导入：'+(err.message||'文件格式不正确'));}}
function rounded(ctx,x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fill();}
async function openShare(){const canvas=document.createElement('canvas');canvas.width=900;canvas.height=1150;const ctx=canvas.getContext('2d');ctx.fillStyle='#faf5ed';ctx.fillRect(0,0,900,1150);const g=ctx.createRadialGradient(690,250,0,690,250,650);g.addColorStop(0,'#eacbc650');g.addColorStop(1,'#faf5ed00');ctx.fillStyle=g;ctx.fillRect(0,0,900,1150);ctx.strokeStyle='#d8bcb0';ctx.lineWidth=2;ctx.strokeRect(45,45,810,1060);ctx.textAlign='center';ctx.fillStyle='#ad686e';ctx.font='45px Georgia';ctx.fillText('♡',450,158);ctx.font='15px sans-serif';ctx.fillText('OUR DAYS  ·  朝暮',450,207);ctx.fillStyle='#66504a';ctx.font='32px "Microsoft YaHei",sans-serif';ctx.fillText(`${settings.name1}  &  ${settings.name2}`,450,312,740);ctx.font='23px "Microsoft YaHei",sans-serif';ctx.fillText('我们已经相爱了',450,390);ctx.fillStyle='#985a63';ctx.font='190px Georgia';ctx.fillText(String(Math.max(0,C.daysBetween(settings.start))),450,590,720);ctx.font='25px serif';ctx.fillText('天',450,651);ctx.fillStyle='#ad9688';ctx.font='18px Georgia';ctx.fillText('SINCE  '+niceDate(settings.start),450,715);ctx.strokeStyle='#e1cbc0';ctx.beginPath();ctx.moveTo(260,770);ctx.lineTo(640,770);ctx.stroke();ctx.fillStyle='#81675f';ctx.font='24px "Microsoft YaHei",sans-serif';const words=[...settings.quote],lines=[];let line='';for(const char of words){if(ctx.measureText(line+char).width>650){lines.push(line);line='';}line+=char;}if(line)lines.push(line);lines.slice(0,4).forEach((v,i)=>ctx.fillText(v,450,830+i*37));ctx.fillStyle='#b59989';ctx.font='italic 24px Georgia';ctx.fillText('All my tomorrows, with you.',450,1030);const blob=await new Promise(r=>canvas.toBlob(r,'image/png'));shareUrl=URL.createObjectURL(blob);openDialog('把幸福，分享出去',`<img class="share-preview" src="${shareUrl}" alt="我们的恋爱纪念卡片"><p class="form-hint" style="margin-top:15px">专属纪念卡片已生成。下载后即可发送给 TA，或分享到你喜欢的平台。</p><div class="form-actions"><button class="button" id="download-share">${icon('share')}下载纪念卡片</button></div>`);$('#download-share').onclick=()=>{download(blob,`朝暮-相爱${C.daysBetween(settings.start)}天.png`);toast('纪念卡片已下载 ♡');};}
async function shareMemory(id){const m=memories.find(m=>m.id===id);if(!m)return;const ext=m.blob.type.split('/')[1];const file=new File([m.blob],m.filename||`我们的回忆.${ext}`,{type:m.blob.type});try{if(navigator.canShare?.({files:[file]})){await navigator.share({title:m.title,text:m.note,files:[file]});}else{download(file,file.name);toast('文件已下载，可以发送给 TA');}}catch(err){if(err.name!=='AbortError')toast('分享失败，请尝试下载后发送');}}
async function toggleFavorite(id){const next=favorites.includes(id)?favorites.filter(x=>x!==id):[...favorites,id];try{persist('our-days-favorites',next);favorites=next;renderMemories();if($('#lightbox').open){const b=$('#lightbox [data-favorite]');if(b){b.innerHTML=`${icon('heart')} ${favorites.includes(id)?'已收藏 · 点击取消':'收藏这份心动'}`;}}toast(favorites.includes(id)?'已收藏这份心动 ♡':'已取消收藏');}catch{toast('收藏失败，请检查浏览器存储空间');}}
document.addEventListener('click',async e=>{const button=e.target.closest('button');if(!button)return;try{if(button.dataset.action){const action=button.dataset.action;if(action==='settings')openSettings(); if(action==='connect-cloud'){const room=e.target.closest('form')?.querySelector('[name=room]')?.value||''; if(!/^[A-Za-z0-9_-]{6,40}$/.test(room)) toast('邀请码需为 6-40 位字母、数字、下划线或短横线'); else {CloudSync.setRoom(room); toast(CloudSync.endpoint?'共享空间已连接':'已保存邀请码，等待云函数地址配置'); closeDialog();}} if(action==='disconnect-cloud'){CloudSync.setRoom(''); toast('已断开共享空间'); closeDialog();}if(action==='event')openEvent();if(action==='upload')openUpload();if(action==='close')closeDialog();if(action==='close-lightbox')closeLightbox();if(action==='share')await openShare();if(action==='export')await exportBackup(button);if(action==='import')$('#import-file').click();if(action==='toggle-demo'){persist('our-days-hide-demo',!hideDemo);hideDemo=!hideDemo;renderMemories();openSettings();toast(hideDemo?'示例照片已隐藏':'示例照片已显示');}}
if(button.dataset.filter){filter=button.dataset.filter;$$('.filter').forEach(b=>{b.classList.toggle('active',b===button);b.setAttribute('aria-pressed',String(b===button));});renderMemories();}
if(button.dataset.open)openMemory(button.dataset.open);
if(button.dataset.favorite)await toggleFavorite(button.dataset.favorite);
if(button.dataset.shareMemory)await shareMemory(button.dataset.shareMemory);
if(button.dataset.deleteEvent&&confirm('删除这个纪念日？')){const next=events.filter(v=>v.id!==button.dataset.deleteEvent);persist('our-days-events',next);events=next;renderEvents();toast('纪念日已删除');}
if(button.dataset.deleteMemory&&confirm('删除这段回忆及其照片或视频？此操作不能撤销。')){const target=memories.find(x=>x.id===button.dataset.deleteMemory); if(target?.remote&&CloudSync?.configured()) await CloudSync.remove(button.dataset.deleteMemory); await MemoryStore.remove(button.dataset.deleteMemory);closeLightbox();await reloadMedia();toast('这段回忆已删除');}
}catch(err){toast('操作未完成：'+(err.message||'请稍后重试'));}});
$('#search').oninput=e=>{search=e.target.value;renderMemories();};$('#import-file').onchange=async e=>{await importBackup(e.target.files[0]);e.target.value='';};
$('#editor').addEventListener('cancel',e=>{e.preventDefault();closeDialog();});$('#lightbox').addEventListener('cancel',e=>{e.preventDefault();closeLightbox();});
for(const d of [$('#editor'),$('#lightbox')])d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom){d.id==='editor'?closeDialog():closeLightbox();}}});
$$('nav a').forEach(a=>a.addEventListener('click',()=>{$$('nav a').forEach(v=>v.classList.toggle('active',v===a));}));
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){$$('nav a').forEach(a=>a.classList.toggle('active',a.hash==='#'+e.target.id));}}),{rootMargin:'-15% 0px -65% 0px'});['home','anniversaries','memories'].forEach(id=>observer.observe(document.getElementById(id)));
const motionReduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
if(!motionReduced){
const revealItems=$$('.poetry-strip,.section-heading,.anniversary-grid,.memory-toolbar,.memory-grid,.closing');
revealItems.forEach(item=>item.classList.add('motion-reveal'));
const revealObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');revealObserver.unobserve(entry.target);}}),{threshold:.08,rootMargin:'0px 0px -8%'});
revealItems.forEach(item=>revealObserver.observe(item));
}
renderSettings();renderEvents();renderMemories();let lastDay=C.localDate();setInterval(()=>{updateCounter();if(lastDay!==C.localDate()){lastDay=C.localDate();renderEvents();}},1000);
MemoryStore.open().then(async()=>{dbReady=true;await reloadMedia();}).catch(()=>toast('浏览器存储未能打开。请通过启动脚本访问，或允许本站使用存储。'));





