'use strict';
async function compressCover(file){
  const source=await createImageBitmap(file);
  const max=1600, scale=Math.min(1,max/source.width,max/source.height);
  const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(source.width*scale));canvas.height=Math.max(1,Math.round(source.height*scale));
  canvas.getContext('2d').drawImage(source,0,0,canvas.width,canvas.height);source.close();
  const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',.82));
  if(!blob)throw Error('图片压缩失败，请换一张图片');
  return blob;
}
window.CloudSync={endpoint:window.LOVE_SYNC_ENDPOINT||'',room:localStorage.getItem('our-days-room')||'',setRoom(r){this.room=r.trim();this.room?localStorage.setItem('our-days-room',this.room):localStorage.removeItem('our-days-room')},configured(){return!!(this.endpoint&&this.room)},async call(action,payload={}){if(!this.configured())throw Error('尚未连接共享空间');const r=await fetch(this.endpoint,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,room:this.room,...payload})}),d=await r.json().catch(()=>({}));if(!r.ok||d.error)throw Error(d.error||'云端请求失败');return d},async list(){return((await this.call('list')).items||[]).map(x=>({...x,id:x.id||x._id,kind:x.filename==='note.txt'?'text':x.kind}))},async upload(meta,file){if(!file)return this.call('upload',{meta,data:'data:text/plain;base64,dGV4dA=='});const data=await new Promise((res,rej)=>{const x=new FileReader();x.onload=()=>res(x.result);x.onerror=()=>rej(x.error);x.readAsDataURL(file)});return this.call('upload',{meta,media:{data,name:file.name||meta.filename}})},async uploadCover(file){const blob=await compressCover(file);const data=await new Promise((res,rej)=>{const x=new FileReader();x.onload=()=>res(x.result);x.onerror=()=>rej(x.error);x.readAsDataURL(blob)});return this.call('uploadCover',{media:{data,name:'cover.jpg'}})},async remove(id){return this.call('delete',{id})},async listReplies(memoryId){return this.call('listReplies',{memoryId})},async createReply(payload){return this.call('createReply',payload)},async updateReply(payload){return this.call('updateReply',payload)},async deleteReply(id,authorSlot){return this.call('deleteReply',{id,authorSlot})}};
