'use strict';
(()=>{
let memory=null,settings=null,items=[],timer=0,requestToken=0,replyTarget=null,editing=null,removed=new Set(),busy=false;
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function author(slot){return slot==='name2'?settings.name2:settings.name1;}
function selected(){return Replies.selectedAuthor();}
function shell(){const host=$('#lightbox-content .lightbox-detail');if(!host||$('#reply-section'))return;host.insertAdjacentHTML('beforeend',`<section id="reply-section" class="reply-section"><div class="reply-heading"><div><span>BETWEEN US</span><h3>回应这一刻</h3></div><button type="button" class="reply-refresh" data-refresh-replies>刷新</button></div><div id="reply-identity"></div><div id="reply-list" class="reply-list"><p class="reply-empty">正在读取回复…</p></div><div id="reply-composer"></div></section>`);renderIdentity();renderComposer();}
function renderIdentity(){const root=$('#reply-identity');if(!root)return;const slot=selected();root.innerHTML=`<div class="reply-identity"><span>${slot?`正在以 <strong>${esc(author(slot))}</strong> 回复`:'回复前，请选择你是谁'}</span><div><button type="button" class="${slot==='name1'?'active':''}" data-author-slot="name1">${esc(settings.name1)}</button><button type="button" class="${slot==='name2'?'active':''}" data-author-slot="name2">${esc(settings.name2)}</button></div></div>`;}
function renderList(){const root=$('#reply-list');if(!root)return;const rows=Replies.flattenForDisplay(items),byId=new Map(items.map(x=>[x.id,x]));if(!rows.length){root.innerHTML='<p class="reply-empty">还没有回复，写下第一句话吧。</p>';return;}root.innerHTML=rows.map(x=>{const mine=selected()===x.authorSlot,to=byId.get(x.replyToId),images=(x.images||[]).map(i=>`<a href="${esc(i.url)}" target="_blank" rel="noopener"><img src="${esc(i.url)}" alt="${esc(i.filename||'回复图片')}" loading="lazy"></a>`).join('');return `<article class="reply-card ${x.deleted?'is-deleted':''}" style="--reply-depth:${Math.min(x.visualDepth||0,2)}" data-reply-id="${esc(x.id)}"><header><strong>${esc(x.authorName||author(x.authorSlot))}</strong><time>${esc(Replies.formatReplyTime(x.createdAt))}</time></header>${to&&x.parentId?`<div class="reply-to-label">回复 ${esc(to.authorName||author(to.authorSlot))}</div>`:''}${x.deleted?'<p class="reply-deleted">该回复已删除</p>':`${x.text?`<p>${esc(x.text)}</p>`:''}${images?`<div class="reply-images">${images}</div>`:''}<footer><button type="button" data-reply-to="${esc(x.id)}">回复</button>${mine?`<button type="button" data-edit-reply="${esc(x.id)}">编辑</button><button type="button" data-delete-reply="${esc(x.id)}">删除</button>`:''}</footer>`}</article>`;}).join('');}
function renderComposer(){const root=$('#reply-composer');if(!root)return;const existing=editing?(editing.images||[]).filter(i=>!removed.has(i.fileID)):[];root.innerHTML=`${replyTarget?`<div class="reply-target">正在回复：${esc(replyTarget.authorName||author(replyTarget.authorSlot))}<button type="button" data-cancel-target>取消</button></div>`:''}${editing?`<div class="reply-target">正在编辑自己的回复<button type="button" data-cancel-edit>取消</button></div>`:''}<form id="reply-form"><textarea name="replyText" maxlength="1000" placeholder="写下想对 TA 说的话……">${esc(editing?.text||'')}</textarea>${existing.length?`<div class="reply-existing-images">${existing.map(i=>`<button type="button" data-remove-reply-image="${esc(i.fileID)}"><img src="${esc(i.url)}" alt=""><span>移除</span></button>`).join('')}</div>`:''}<label class="reply-file-label">添加图片<input id="reply-files" type="file" accept="image/jpeg,image/png,image/webp,image/gif" multiple></label><div id="reply-file-preview" class="reply-images"></div><p class="reply-hint">可只写文字或只发图片，最多 10 张，单张不超过 20MB。</p><button class="button reply-submit" type="submit">${editing?'保存修改':'发送回复'} ♡</button><p id="reply-error" class="form-error" hidden></p></form>`;const input=$('#reply-files');input.onchange=()=>{const preview=$('#reply-file-preview');try{Replies.validateFiles(input.files);preview.innerHTML=[...input.files].map(f=>`<span>${esc(f.name)}</span>`).join('');}catch(e){input.value='';showError(e.message);}};$('#reply-form').onsubmit=submit;}
function showError(message){const el=$('#reply-error');if(el){el.textContent=message;el.hidden=false;}}
async function refresh(){if(!memory||!CloudSync.configured())return;const token=++requestToken;try{const data=await CloudSync.listReplies(memory.id);if(token!==requestToken)return;items=data.items||[];renderList();}catch(e){const root=$('#reply-list');if(root)root.innerHTML=`<p class="reply-empty">${esc(e.message||'回复加载失败')}</p>`;}}
async function submit(event){event.preventDefault();if(busy)return;try{const slot=selected();if(!slot)throw Error('请先选择你是谁');const form=event.currentTarget,text=form.replyText.value.trim(),files=[...form.querySelector('#reply-files').files];Replies.validateFiles(files);const images=await Replies.filePayloads(files);if(!text&&!images.length&&!editing?.images?.some(i=>!removed.has(i.fileID)))throw Error('请填写文字或选择图片');busy=true;form.querySelector('[type=submit]').disabled=true;if(editing)await CloudSync.updateReply({id:editing.id,authorSlot:slot,text,addedImages:images,removedFileIDs:[...removed]});else await CloudSync.createReply({memoryId:memory.id,parentId:replyTarget?.id||'',replyToId:replyTarget?.id||'',authorSlot:slot,authorName:author(slot),text,images});replyTarget=null;editing=null;removed.clear();await refresh();renderComposer();}catch(e){showError(e.message||'发送失败，请重试');}finally{busy=false;const b=$('#reply-form [type=submit]');if(b)b.disabled=false;}}
async function click(event){const button=event.target.closest('button');if(!button||!memory)return;if(button.dataset.authorSlot){Replies.setSelectedAuthor(button.dataset.authorSlot);renderIdentity();renderList();return;}if(button.hasAttribute('data-refresh-replies'))return refresh();if(button.dataset.replyTo){replyTarget=items.find(x=>x.id===button.dataset.replyTo)||null;editing=null;removed.clear();renderComposer();$('#reply-form textarea')?.focus();}if(button.hasAttribute('data-cancel-target')){replyTarget=null;renderComposer();}if(button.dataset.editReply){editing=items.find(x=>x.id===button.dataset.editReply)||null;replyTarget=null;removed.clear();renderComposer();$('#reply-form textarea')?.focus();}if(button.hasAttribute('data-cancel-edit')){editing=null;removed.clear();renderComposer();}if(button.dataset.removeReplyImage){removed.add(button.dataset.removeReplyImage);renderComposer();}if(button.dataset.deleteReply&&confirm('删除这条回复？')){try{await CloudSync.deleteReply(button.dataset.deleteReply,selected());await refresh();}catch(e){alert(e.message||'删除失败');}}}
function open(nextMemory,nextSettings){close();memory=nextMemory;settings=nextSettings;if(memory.demo)return;shell();if(!CloudSync.configured()){$('#reply-list').innerHTML='<p class="reply-empty">连接共享空间后，就可以一起回复这段日常。</p>';return;}refresh();timer=setInterval(refresh,15000);}
function close(){memory=null;settings=null;items=[];replyTarget=null;editing=null;removed.clear();requestToken++;if(timer)clearInterval(timer);timer=0;}
document.addEventListener('click',click);window.addEventListener('focus',()=>{if(memory)refresh();});window.addEventListener('online',()=>{if(memory)refresh();});
window.ReplyUI={open,close,refresh};
})();
