'use strict';
(()=>{
let queue=[],urls=[],controller=null,lastMeta=null,generation=0,submitting=false;
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const size=n=>n>1048576?`${(n/1048576).toFixed(1)} MB`:`${Math.ceil(n/1024)} KB`;
function cleanup(){generation++;controller?.abort();urls.forEach(URL.revokeObjectURL);urls=[];submitting=false;}
function active(run,signal){if(run!==generation||signal.aborted)throw Error('上传已取消');}
function status(item){return({queued:'等待上传',preparing:'正在准备并压缩…',ready:'准备完成',uploading:'正在上传…',complete:'上传完成',failed:'上传失败'}[item.state]||item.state);}
function render(){urls.forEach(URL.revokeObjectURL);urls=[];const root=$('#upload-queue-list');if(!root)return;root.innerHTML=queue.map(item=>{const preview=item.poster||item.prepared||item.file,url=URL.createObjectURL(preview);urls.push(url);const media=item.poster||!item.file.type.startsWith('video/')?`<img src="${url}" alt="">`:`<video src="${url}" muted></video>`;return `<article class="upload-row ${item.state}">${media}<div><strong>${esc(item.file.name)}</strong><small>${size(item.file.size)} · ${status(item)}</small>${item.error?`<em>${esc(item.error)}</em>`:''}${item.file.type.startsWith('video/')?`<label class="poster-picker">选择视频封面<input type="file" accept="image/jpeg,image/png,image/webp" data-poster-for="${item.id}"></label>`:''}</div>${item.state==='failed'?`<button type="button" data-retry-upload="${item.id}">重试</button>`:''}</article>`;}).join('');}
function open(){cleanup();queue=[];controller=new AbortController();$('#dialog-title').textContent='把此刻，留给以后的我们';$('#dialog-content').innerHTML=`<form id="enhanced-upload" class="metadata-form"><label class="field upload-zone">选择照片或视频<input id="enhanced-files" type="file" accept="image/jpeg,image/png,image/webp,image/gif,video/mp4,video/webm,video/ogg" multiple><span class="form-hint">照片默认自动压缩，一次最多 10 个；单个视频不超过 100 MB。</span></label><div id="upload-queue-list" class="upload-queue-list"></div><label class="field">标题<input name="title" maxlength="100" placeholder="给这段回忆起个名字"></label><div class="form-grid"><label class="field">拍摄日期<input name="capturedAt" type="date" value="${new Date().toLocaleDateString('en-CA')}" required></label><label class="field">地点<input name="place" maxlength="60"></label></div><label class="field">人物<input name="people" placeholder="用逗号分隔"></label><label class="field">标签<input name="tags" placeholder="用逗号分隔"></label><label class="field">备注<textarea name="note" maxlength="500"></textarea></label><p id="form-error" class="form-error"></p><div class="form-actions"><button type="button" class="button button-outline" data-action="close">取消</button><button class="button" type="submit">开始珍藏</button></div></form>`;if(!$('#editor').open)$('#editor').showModal();document.body.classList.add('no-scroll');$('#enhanced-files').onchange=e=>{if(submitting){e.target.value='';return;}try{cleanup();controller=new AbortController();queue=UploadQueue.create(e.target.files);render();}catch(error){e.target.value='';$('#form-error').textContent=error.message;}};$('#enhanced-upload').onsubmit=submit;$('#editor').addEventListener('close',cleanup,{once:true});}
async function processItem(item,meta){const run=generation,signal=controller.signal;if(item.state==='failed')item=UploadQueue.transition(item,'queued');const index=queue.findIndex(x=>x.id===item.id);try{active(run,signal);queue[index]=UploadQueue.transition(item,'preparing');render();let file=item.file,poster=item.poster;if(file.type.startsWith('image/'))file=await MediaPreparation.prepareImage(file,{signal});if(file.type.startsWith('video/')&&!poster)poster=await MediaPreparation.captureVideoPoster(file,{signal});active(run,signal);queue[index]=UploadQueue.transition(queue[index],'ready',{prepared:file,poster});queue[index]=UploadQueue.transition(queue[index],'uploading');render();const record={id:item.id,...meta,room:CloudSync?.room||'',kind:file.type.startsWith('video/')?'video':'image',filename:file.name,createdAt:Date.now(),blob:file};await MemoryStore.write([record]);active(run,signal);if(CloudSync?.configured()){const result=await CloudSync.upload(record,file,poster);active(run,signal);if(result.item){Object.assign(record,{cloudId:result.item.cloudId||result.item._id||result.item.id,createdAt:result.item.createdAt||record.createdAt,posterUrl:result.item.posterUrl||''});await MemoryStore.write([record]);}}active(run,signal);queue[index]=UploadQueue.transition(queue[index],'complete');render();}catch(error){if(run!==generation)return;queue[index]={...queue[index],state:'failed',error:error.message||'上传失败'};render();}}
async function submit(event){event.preventDefault();if(submitting)return;submitting=true;const form=event.currentTarget,button=form.querySelector('[type=submit]');button.disabled=true;try{const f=new FormData(form),title=String(f.get('title')||'').trim()||String(f.get('note')||'').trim().slice(0,30)||'日常记录';lastMeta=MemoryMetadata.validate({title,capturedAt:f.get('capturedAt'),place:f.get('place'),people:f.get('people'),tags:f.get('tags'),note:f.get('note'),authorSlot:Replies.selectedAuthor()},{today:new Date().toLocaleDateString('en-CA')});if(!queue.length){const note=new File([lastMeta.note||lastMeta.title],'note.txt',{type:'text/plain'}),record={id:crypto.randomUUID(),...lastMeta,room:CloudSync?.room||'',kind:'text',filename:'note.txt',createdAt:Date.now(),blob:note};await MemoryStore.write([record]);if(CloudSync?.configured()){const result=await CloudSync.upload(record,note);if(result.item){record.cloudId=result.item.cloudId||result.item._id||result.item.id;await MemoryStore.write([record]);}}location.reload();return;}for(const item of [...queue])if(item.state==='queued'||item.state==='failed')await processItem(item,lastMeta);if(queue.every(x=>x.state==='complete'))setTimeout(()=>location.reload(),500);}catch(error){$('#form-error').textContent=error.message||'上传失败';}finally{submitting=false;button.disabled=false;}}
document.addEventListener('change',async event=>{const input=event.target.closest('[data-poster-for]');if(!input?.files[0]||submitting)return;const run=generation,index=queue.findIndex(x=>x.id===input.dataset.posterFor);try{const poster=await MediaPreparation.preparePoster(input.files[0],controller.signal);if(run!==generation)return;queue[index]={...queue[index],poster};render();}catch(error){if(run===generation){queue[index]={...queue[index],error:error.message};render();}}},true);
document.addEventListener('click',event=>{const upload=event.target.closest('[data-action="upload"]');if(upload){event.preventDefault();event.stopImmediatePropagation();open();return;}const retry=event.target.closest('[data-retry-upload]');if(retry){event.preventDefault();event.stopImmediatePropagation();const item=queue.find(x=>x.id===retry.dataset.retryUpload);if(item&&lastMeta&&!submitting)processItem(item,lastMeta);}},true);
})();
